In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         1         0         1            7                1   
1         0         0         0         0            7                1   
2         0         1         0         1            7                2   
3         1         0         0         0            7                3   
4         0         1         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Creating Targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         1         0         1            7                1   
1         0         0         0         0            7                1   
2         0         1         0         1            7                2   
3         1         0         0         0            7                3   
4         0         1         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
data_preprocessed['Excessive Absenteeism'].value_counts()

0    381
1    319
Name: Excessive Absenteeism, dtype: int64

In [10]:
data_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Daily Work Load Average','Distance to Work','Day of the Week' ], axis = 1)

In [11]:
data_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         1         0         1            7   
1         0         0         0         0            7   
2         0         1         0         1            7   
3         1         0         0         0            7   
4         0         1         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
data_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         1         0         1            7   
1           0         0         0         0            7   
2           0         1         0         1            7   
3           1         0         0         0            7   
4           0         1         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         1         0         1            5   
699         0         1         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [13]:
unscaled_inputs = data_targets.iloc[:,:-1]

## Standardizing the data

In [14]:
#from sklearn.preprocessing import StandardScaler

#scaler = StandardScaler()

In [15]:
#scaler.fit(unscale_inputs)

In [16]:
#scaled_inputs = scaler.transform(unscale_inputs)

In [17]:
#scaled_inputs

In [18]:
#scaled_inputs.shape

## Custome scaler to avoid standardizing dummy variables

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [20]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [21]:
columns_to_omit = ['Absenteeism Time in Hours','Daily Work Load Average','Distance to Work','Day of the Week']

In [22]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [23]:
scaler = CustomScaler(columns_to_scale)

In [24]:
scaler.fit(unscaled_inputs)

C:\Users\shiva\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
                      'Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Education', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [25]:
scaled_inputs = scaler.transform(unscaled_inputs)

In [26]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0   -0.577350  0.661341 -0.314485  0.821365     0.182726   
1   -0.577350 -1.512080 -0.314485 -1.217485     0.182726   
2   -0.577350  0.661341 -0.314485  0.821365     0.182726   
3    1.732051 -1.512080 -0.314485 -1.217485     0.182726   
4   -0.577350  0.661341 -0.314485  0.821365     0.182726   
..        ...       ...       ...       ...          ...   
695  1.732051 -1.512080 -0.314485 -1.217485    -0.388293   
696  1.732051 -1.512080 -0.314485 -1.217485    -0.388293   
697  1.732051 -1.512080 -0.314485 -1.217485    -0.388293   
698 -0.577350  0.661341 -0.314485  0.821365    -0.388293   
699 -0.577350  0.661341 -0.314485  0.821365    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
1                 -1.574681  2.130803         1.002633  -0.447980 -0.019280   
2                 -0.654143  0.248310         1.002633  -0.447980 -0.919030   
3                  0.854936  0.405184        -0.643782  -0.447980  0.880469   
4                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186   2.232242  0.880469   
696                0.040034 -1.320435        -0.643782  -0.447980 -0.019280   
697                1.624567 -1.320435        -0.408580   2.232242 -0.919030   
698                0.190942 -0.692937        -0.408580   2.232242 -0.919030   
699                1.036026  0.562059        -0.408580  -0.447980 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

## Splitting the data


In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 5)

In [29]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [30]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [32]:
reg = LogisticRegression()

In [33]:
reg.fit(x_train,  y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
reg.score(x_train, y_train)

0.7803571428571429

In [35]:
reg.intercept_

array([-0.32615577])

In [36]:
reg.coef_

array([[ 2.21964489,  1.46348292,  0.66994374, -0.11076986,  0.09894442,
         0.75936025, -0.23643469,  0.31916604,  0.11118387,  0.44590448,
        -0.37023354]])

In [38]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficients'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficients
0                 Reason_1      2.219645
1                 Reason_2      1.463483
2                 Reason_3      0.669944
3                 Reason_4     -0.110770
4              Month Value      0.098944
5   Transportation Expense      0.759360
6                      Age     -0.236435
7          Body Mass Index      0.319166
8                Education      0.111184
9                 Children      0.445904
10                    Pets     -0.370234

In [43]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficients
0                Intercept     -0.326156
1                 Reason_1      2.219645
2                 Reason_2      1.463483
3                 Reason_3      0.669944
4                 Reason_4     -0.110770
5              Month Value      0.098944
6   Transportation Expense      0.759360
7                      Age     -0.236435
8          Body Mass Index      0.319166
9                Education      0.111184
10                Children      0.445904
11                    Pets     -0.370234

In [44]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficients)

In [45]:
summary_table

Feature name  Coefficients  Odds Ratio
0                Intercept     -0.326156    0.721693
1                 Reason_1      2.219645    9.204062
2                 Reason_2      1.463483    4.320983
3                 Reason_3      0.669944    1.954127
4                 Reason_4     -0.110770    0.895145
5              Month Value      0.098944    1.104005
6   Transportation Expense      0.759360    2.136909
7                      Age     -0.236435    0.789437
8          Body Mass Index      0.319166    1.375980
9                Education      0.111184    1.117600
10                Children      0.445904    1.561902
11                    Pets     -0.370234    0.690573

In [46]:
summary_table.sort_values('Odds Ratio', ascending = False)

Feature name  Coefficients  Odds Ratio
1                 Reason_1      2.219645    9.204062
2                 Reason_2      1.463483    4.320983
6   Transportation Expense      0.759360    2.136909
3                 Reason_3      0.669944    1.954127
10                Children      0.445904    1.561902
8          Body Mass Index      0.319166    1.375980
9                Education      0.111184    1.117600
5              Month Value      0.098944    1.104005
4                 Reason_4     -0.110770    0.895145
7                      Age     -0.236435    0.789437
0                Intercept     -0.326156    0.721693
11                    Pets     -0.370234    0.690573

## Testing the Model

In [47]:
reg.score(x_test, y_test)

0.7357142857142858

In [51]:
proba = reg.predict_proba(x_test)
proba

array([[0.94861143, 0.05138857],
       [0.16159688, 0.83840312],
       [0.04056104, 0.95943896],
       [0.19028075, 0.80971925],
       [0.76441867, 0.23558133],
       [0.31689602, 0.68310398],
       [0.78840973, 0.21159027],
       [0.88678066, 0.11321934],
       [0.6003451 , 0.3996549 ],
       [0.89529461, 0.10470539],
       [0.77933723, 0.22066277],
       [0.42208296, 0.57791704],
       [0.91015263, 0.08984737],
       [0.50078054, 0.49921946],
       [0.778831  , 0.221169  ],
       [0.80710472, 0.19289528],
       [0.90271555, 0.09728445],
       [0.76178837, 0.23821163],
       [0.15385162, 0.84614838],
       [0.58102639, 0.41897361],
       [0.10066562, 0.89933438],
       [0.78840973, 0.21159027],
       [0.13561654, 0.86438346],
       [0.82772839, 0.17227161],
       [0.80710472, 0.19289528],
       [0.2563323 , 0.7436677 ],
       [0.34642658, 0.65357342],
       [0.34756346, 0.65243654],
       [0.7352182 , 0.2647818 ],
       [0.27010887, 0.72989113],
       [0.

In [52]:
proba[:,1]

array([0.05138857, 0.83840312, 0.95943896, 0.80971925, 0.23558133,
       0.68310398, 0.21159027, 0.11321934, 0.3996549 , 0.10470539,
       0.22066277, 0.57791704, 0.08984737, 0.49921946, 0.221169  ,
       0.19289528, 0.09728445, 0.23821163, 0.84614838, 0.41897361,
       0.89933438, 0.21159027, 0.86438346, 0.17227161, 0.19289528,
       0.7436677 , 0.65357342, 0.65243654, 0.2647818 , 0.72989113,
       0.18047783, 0.88282112, 0.07894648, 0.95139977, 0.18047783,
       0.0921844 , 0.14645064, 0.38389815, 0.00660572, 0.95642011,
       0.04283463, 0.45347007, 0.60367797, 0.64706483, 0.71332689,
       0.39060129, 0.68970087, 0.37836685, 0.65881462, 0.7436677 ,
       0.10236036, 0.49290321, 0.07894648, 0.57120645, 0.58708202,
       0.62093904, 0.36406039, 0.19335362, 0.24590739, 0.18047783,
       0.42728013, 0.23053211, 0.18898571, 0.89630099, 0.07894648,
       0.2359914 , 0.18469389, 0.23053211, 0.221169  , 0.57101141,
       0.9348302 , 0.18047783, 0.32196387, 0.07894648, 0.13617